import type { Metadata } from 'next'
import styles from '../page.module.css'

export const metadata: Metadata = {
  title: 'Route 2',
  description: 'Generated by create next app'
}

export default function RootLayout(props
: {
  children: React.ReactNode
  left: React.ReactNode
  right: React.ReactNode
  
}) {
  return (
    <>
      {props.children}
      <div>
        <div className={styles.card}>{props.left}</div>
        <div className={styles.card}>{props.right}</div>
      </div>
    </>
  )
}