import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
  icons: {
    icon: "/icons/next-icon.svg"
  }
}

export default function RootLayout(props: {
  children: React.ReactNode
  auth: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {props.auth}
        {props.children}
      </body>
    </html>
  )
}
