import styles from '../page.module.css'
import React from 'react'

import type { Metadata } from 'next'
import Link from 'next/link'

import { waiting } from 'app/utils'

export const metadata: Metadata = {
  title: 'Route 1',
  description: 'Generated by create next app',
}

const Route1 = async () => {
  await waiting()

  return (
    <main className={styles.main}>
      <h1>Hello, Route 1!</h1>
      <div className={styles.grid}>
        <Link
          href="./"
          className={styles.card}
        >
          <h2>
            Homepage <span>-&gt;</span>
          </h2>
          <p>Learn about Next.js in an interactive course with&nbsp;quizzes!</p>
        </Link>

        <Link
          href="./route2"
          className={styles.card}
        >
          <h2>
            Route 2 <span>-&gt;</span>
          </h2>
          <p>Find in-depth information about Next.js features and API.</p>
        </Link>
      </div>
    </main>
  )
}

export default Route1